### ISSUE TITLE
[Question] Is it possible to pass a XML schema to provide new elements to insert?

### ISSUE THREAD

**Issue by Nathan961207** [captain-igloo/react-xml-editor#4]

**Comment by captain-igloo** [comment]
I'm not sure what you mean, please explain what you're trying to do.

**Comment by Nathan961207** [comment]
I haven´t tried it yet. 

This is an XML editor so I was wondering if it is possible to use an XML schema to add more elements into the editor?

**Comment by captain-igloo** [comment]
At the moment you can use Util.newElementBefore, Util.newElementAfter, Util.newElementChild to add new elements.  Or you can write your own custom function similar to one of those and add it to your document spec.  There is no built-in ability to add an XML fragment yet.

But again, I don't understand what you mean by "use an XML schema to add more elements".  Please provide more information or an example.
