### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by vizardkill** [captain-igloo/react-xml-editor#5]
It would be possible if you could set up an online example in CodeSanbox to understand how the editor works, I have done all the steps but nevertheless it does not look like in the images, and I do not see how to create an xml from scratch

**Comment by captain-igloo** [comment]
Try the following:

```
git clone https://github.com/captain-igloo/react-xml-editor.git
cd react-xml-editor
npm ci
npm run build
npm run build-demo
```
then open demo/index.html in your browser.

As for creating xml from scratch, I think you'll need to start with at least an empty root element like "`<root />`".
